config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    [username, password] == [ENV['BASIC_AUTH_USER'], ENV['BASIC_AUTH_PASS']]
  end
  root 'projects#index'
  post 'wistia-project' => 'projects#fetch_project_from_wistia', as: :fetch_project_from_wistia
  post 'wistia-medias/:project_id' => 'projects#fetch_video_urls_from_wistia', as: :fetch_video_urls_from_wistia
  get 'download/:project_id' => 'projects#download', as: :download_project_csv
  delete 'projects/:id' => 'projects#destroy', as: :projects_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :videos, dependent: :destroy
  validates_presence_of :hashed_id
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :project

  def self.to_csv
    attributes = %w{project_id name hashed_id url}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      current_scope.each do |video|
        csv << attributes.map{ |attr| video.send(attr) }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USER'], password: ENV['BASIC_AUTH_PASS']
  require 'wistia_library'

  def index
    @projects = Project.all
    @project = Project.new
  end

  def fetch_project_from_wistia
    # call wistia, create project, store videos
    @project = Project.new(project_params)
    if @project.save
      wistia_project = WistiaLibrary.call_wistia_with_hashed_id('projects', @project.hashed_id)
      medias = wistia_project['medias']
      medias.each do |media|
        Video.create(project: @project, name: media['name'], hashed_id: media['hashed_id'])
      end
      @project.update_attributes(name: wistia_project['name'], video_count: @project.videos.count)
      flash[:success] = "You did it!"
      redirect_to '/'
    else
      flash[:error] = "That didn't work. Check the logs if you think it should have."
      redirect_to '/'
    end
  end

  def fetch_video_urls_from_wistia
    # call wistia for each project video and update with URL
    WistiaMediaWorker.perform_async(params[:project_id])
    flash[:success] = "Job started. Check Sidekiq."
    redirect_to '/'
  end

  def download
    @project = Project.find(params[:project_id])
    @videos = Video.where(project_id: params[:project_id])
    
    respond_to do |format|
      format.csv { send_data @videos.to_csv, filename: "videos-#{@project.id}-#{@project.hashed_id}.csv" }
    end
  end

  def destroy
    if Project.find(params[:id]).destroy
      flash[:success] = "Project was deleted"
      redirect_to '/'
    else
      flash[:error] = "Error deleting project"
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :hashed_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WistiaArchiver
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |key, value|
      = content_tag :div, value, class: "flash #{key}"
    = yield

app/views/projects/_form.html.haml
= form_for @project, url: fetch_project_from_wistia_path do |f|
  = f.label :hashed_id, "Enter a Project's hashedId"
  = f.text_field :hashed_id

  = f.submit "Fetch details from Wistia"

app/views/projects/index.html.haml
%h2 Get a new project
= render 'form'

%h2 Existing projects
%table
  %tr
    %th Project ID
    %th Name
    %th Hashed ID
    %th Videos
    %th Actions
  - @projects.reverse_each do |project|
    %tr
      %td= project.id
      %td= project.name
      %td= project.hashed_id
      %td= project.video_count
      %td
        = link_to "Fetch & Add file URLs", fetch_video_urls_from_wistia_path(project), method: :post, data: { confirm: "Due to Wistia's rate limit, this will take at least #{Time.at(project.video_count*0.7).utc.strftime('%H hours, %M minutes, and %S seconds')}. Click OK to start a background job."}
        |
        = link_to "Download CSV", "#{request.base_url}/download/#{project.id}.csv"
        |
        = link_to "Delete", projects_delete_path(project), method: :delete, data: { confirm: 'Are you sure?'}, class: 'delete'